services:
  - type: web
    name: radisense-backend
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn predictor.wsgi --bind 0.0.0.0:$PORT --workers 1 --timeout 180 --max-requests 1 --max-requests-jitter 1
    envVars:
      - key: DJANGO_SECRET_KEY
        value: radisense-secret-key-2024
      - key: DEBUG
        value: "False"
      - key: MODEL_PATH
        value: model/fracture_model_final.pth
      - key: PYTHON_VERSION
        value: 3.11.9